language: dart
dart:
  - dev
  - stable

script:
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test
  - pub run dart_dev coverage --no-html

branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
