language: dart
dart:
  - dev

script:
  - tool/analyze.sh
  - tool/coverage.sh
  - bash <(curl -s https://codecov.io/bash) -f _coverage/coverage.lcov

branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache

env:
  - DARTANALYZER_FLAGS=--fatal-warnings
