language: dart
dart:
  - dev
  - stable

dart_task:
  - test: --platform vm
  - dartanalyzer
  - dartfmt
  - coverage: --no-html

branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
