name: dazza
version: 1.0.0
author: Yakka, LLC <flutter@theyakka.com>
description: A general routing library for Dart.
homepage: https://github.com/theyakka/dazza

environment:
  sdk: ">=2.0.0-dev.69.0 <3.0.0"

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.0
  dart_style: ^1.1.3
  coverage: ^0.12.1