name: dazza
version: 1.0.0
author: Yakka, LLC <apps@theyakka.com>
description: A general routing library for Dart.
homepage: https://github.com/theyakka/dazza

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  test: ^1.12.0
  dart_style: ^1.3.3
  coverage: ^0.13.6